### ISSUE TITLE
PROJECTED PRINCIPAL COMPONENT ANALYSIS IN FACTOR MODELS

### ISSUE THREAD

**Issue by ssdagonidong** [LeetaH666/Notes#2]
您好，我是辽大的学生，您有兴趣弄一下这篇论文的程序吗？可以给我一下您的联系方式吗？

**Comment by LeetaH666** [comment]
您指的是Fan (2016)吗？我最近可能没时间复现这篇。

**Comment by ssdagonidong** [comment]
真的不能帮一下忙吗，我最近太需要这篇论文了，我都已经把过程整理好了，就差程序了

**Comment by LeetaH666** [comment]
抱歉，我最近确实没时间弄这个。如果只差程序的话您可以找你们学校计系的人帮忙呀。

**Comment by ssdagonidong** [comment]
好吧，麻烦了谢了哈，你真的很厉害，打扰你啦
